const dbHelper = require('./db-helper');

const ALL_50_FIRS = [
  { case_number: "KAR/KAL/2024/0330", date_filed: "2024-06-01", time_filed: "13:09:00", crime_type_code: "hit_and_run", crime_type: "Hit And Run", description: "Speeding vehicle collided with two-wheeler near Murty Circle, Kalaburagi.", status: "open", case_status: "open", district_name: "Kalaburagi", police_station: "Kalaburagi Rural PS", location_name: "Near Murty Circle, Kalaburagi", investigation_office: "Insp. Lohit Lall", accused_name: "Vikram Singh", risk_score: 88 },
  { case_number: "KAR/KAL/2024/0102", date_filed: "2024-06-01", time_filed: "13:09:00", crime_type_code: "hit_and_run", crime_type: "Hit And Run", description: "Speeding vehicle collided with pedestrian near Murty Circle.", status: "open", case_status: "open", district_name: "Kalaburagi", police_station: "Kalaburagi Rural PS", location_name: "Near Murty Circle, Kalaburagi", investigation_office: "Insp. Lohit Lall", accused_name: "Vikram Singh", risk_score: 88 },
  { case_number: "KAR/RAI/2024/0123", date_filed: "2024-06-01", time_filed: "00:10:00", crime_type_code: "vehicle_theft", crime_type: "Vehicle Theft", description: "Stolen motorcycle outside Balay Circle, Raichur.", status: "chargesheeted", case_status: "chargesheeted", district_name: "Raichur", police_station: "Raichur Suburban PS", location_name: "Near Balay Circle, Raichur", investigation_office: "Insp. Jonathan Iyengar", accused_name: "Ramesh Kumar", risk_score: 94 },
  { case_number: "KAR/BEN/2024/1726", date_filed: "2024-06-01", time_filed: "22:52:00", crime_type_code: "drug_offence", crime_type: "Drug Offence", description: "Tactical raid near Wadhwa seizing commercial MDMA payload.", status: "chargesheeted", case_status: "chargesheeted", district_name: "Bengaluru Urban", police_station: "Bengaluru Urban East PS", location_name: "Near Wadhwa, Bengaluru Urban", investigation_office: "Insp. George Gopal", accused_name: "Imran Khan", risk_score: 96 },
  { case_number: "KAR/UDU/2024/0049", date_filed: "2024-06-01", time_filed: "17:21:00", crime_type_code: "senior_citizen_crime", crime_type: "Senior Citizen Crime", description: "Extortion complaint under Senior Citizen Protection Act near Das Marg.", status: "open", case_status: "open", district_name: "Udupi", police_station: "Udupi Rural PS", location_name: "Near Das Marg, Udupi", investigation_office: "Insp. Saanvi Dara", accused_name: "Saanvi Dara", risk_score: 82 },
  { case_number: "KAR/KAL/2024/0106", date_filed: "2024-06-01", time_filed: "13:09:00", crime_type_code: "hit_and_run", crime_type: "Hit And Run", description: "Hit and run collision logged near Murty Circle.", status: "open", case_status: "open", district_name: "Kalaburagi", police_station: "Kalaburagi Rural PS", location_name: "Near Murty Circle, Kalaburagi", investigation_office: "Insp. Lohit Lall", accused_name: "Vikram Singh", risk_score: 88 },
  { case_number: "KAR/BEN/2024/0380", date_filed: "2024-06-01", time_filed: "22:58:00", crime_type_code: "cybercrime", crime_type: "Cybercrime", description: "Phishing scam mimicking banking portal near Gara Zila.", status: "chargesheeted", case_status: "chargesheeted", district_name: "Bengaluru Urban", police_station: "Bengaluru Urban Traffic PS", location_name: "Near Gara Zila, Bengaluru Urban", investigation_office: "Insp. Bhavani Karpe", accused_name: "Bhavani Karpe", risk_score: 85 },
  { case_number: "KAR/RAI/2024/0108", date_filed: "2024-06-01", time_filed: "00:10:00", crime_type_code: "vehicle_theft", crime_type: "Vehicle Theft", description: "Vehicle theft reported near Balay Circle.", status: "chargesheeted", case_status: "chargesheeted", district_name: "Raichur", police_station: "Raichur Suburban PS", location_name: "Near Balay Circle, Raichur", investigation_office: "Insp. Jonathan Iyengar", accused_name: "Ramesh Kumar", risk_score: 94 },
  { case_number: "KAR/BEN/2024/0109", date_filed: "2024-06-01", time_filed: "22:52:00", crime_type_code: "drug_offence", crime_type: "Drug Offence", description: "Narcotics interception near Wadhwa.", status: "chargesheeted", case_status: "chargesheeted", district_name: "Bengaluru Urban", police_station: "Bengaluru Urban East PS", location_name: "Near Wadhwa, Bengaluru Urban", investigation_office: "Insp. George Gopal", accused_name: "Imran Khan", risk_score: 96 },
  { case_number: "KAR/BEN/2024/0747", date_filed: "2024-06-01", time_filed: "01:32:00", crime_type_code: "vehicle_theft", crime_type: "Vehicle Theft", description: "Vehicle theft logged near Keer Circle.", status: "chargesheeted", case_status: "chargesheeted", district_name: "Bengaluru Urban", police_station: "Bengaluru Urban Central PS", location_name: "Near Keer Circle, Bengaluru Urban", investigation_office: "Insp. Radha Virk", accused_name: "Ramesh Kumar", risk_score: 94 },
  { case_number: "KAR/CHI/2024/0901", date_filed: "2024-06-01", time_filed: "23:36:00", crime_type_code: "burglary", crime_type: "Burglary", description: "Housebreaking and gold looting near Ganesh Marg.", status: "open", case_status: "open", district_name: "Chikkamagaluru", police_station: "Chikkamagaluru Market PS", location_name: "Near Ganesh Marg, Chikkamagaluru", investigation_office: "Insp. Bhavna Menon", accused_name: "Vikram Reddy", risk_score: 84 },
  { case_number: "KAR/TUM/2024/0774", date_filed: "2024-06-01", time_filed: "10:25:00", crime_type_code: "drug_offence", crime_type: "Drug Offence", description: "Narcotics contraband raid near Bajaj Chowk.", status: "closed", case_status: "closed", district_name: "Tumakuru", police_station: "Tumakuru Town PS", location_name: "Near Bajaj Chowk, Tumakuru", investigation_office: "Insp. Janaki Bhatia", accused_name: "Imran Khan", risk_score: 96 },
  { case_number: "KAR/BEN/2024/0384", date_filed: "2024-06-01", time_filed: "07:54:00", crime_type_code: "assault", crime_type: "Assault", description: "Physical altercation near Padmanabhan Zila.", status: "under_investigation", case_status: "under_investigation", district_name: "Bengaluru Urban", police_station: "Bengaluru Urban West PS", location_name: "Near Padmanabhan Zila, Bengaluru Urban", investigation_office: "Insp. Mahika Ramachandran", accused_name: "Mahika Ramachandran", risk_score: 78 },
  { case_number: "KAR/BEN/2024/0114", date_filed: "2024-06-01", time_filed: "07:54:00", crime_type_code: "assault", crime_type: "Assault", description: "Physical assault reported near Padmanabhan Zila.", status: "under_investigation", case_status: "under_investigation", district_name: "Bengaluru Urban", police_station: "Bengaluru Urban West PS", location_name: "Near Padmanabhan Zila, Bengaluru Urban", investigation_office: "Insp. Mahika Ramachandran", accused_name: "Mahika Ramachandran", risk_score: 78 },
  { case_number: "KAR/KAL/2024/0115", date_filed: "2024-06-01", time_filed: "13:09:00", crime_type_code: "hit_and_run", crime_type: "Hit And Run", description: "Hit and run logged near Murty Circle.", status: "open", case_status: "open", district_name: "Kalaburagi", police_station: "Kalaburagi Rural PS", location_name: "Near Murty Circle, Kalaburagi", investigation_office: "Insp. Lohit Lall", accused_name: "Vikram Singh", risk_score: 88 },
  { case_number: "KAR/KAL/2024/0116", date_filed: "2024-06-01", time_filed: "13:09:00", crime_type_code: "hit_and_run", crime_type: "Hit And Run", description: "Speeding hit and run near Murty Circle.", status: "open", case_status: "open", district_name: "Kalaburagi", police_station: "Kalaburagi Rural PS", location_name: "Near Murty Circle, Kalaburagi", investigation_office: "Insp. Lohit Lall", accused_name: "Vikram Singh", risk_score: 88 },
  { case_number: "KAR/BEN/2024/0117", date_filed: "2024-06-01", time_filed: "07:54:00", crime_type_code: "assault", crime_type: "Assault", description: "Assault reported near Padmanabhan Zila.", status: "under_investigation", case_status: "under_investigation", district_name: "Bengaluru Urban", police_station: "Bengaluru Urban West PS", location_name: "Near Padmanabhan Zila, Bengaluru Urban", investigation_office: "Insp. Mahika Ramachandran", accused_name: "Mahika Ramachandran", risk_score: 78 },
  { case_number: "KAR/BEN/2024/0118", date_filed: "2024-06-01", time_filed: "07:54:00", crime_type_code: "assault", crime_type: "Assault", description: "Assault incident near Padmanabhan Zila.", status: "under_investigation", case_status: "under_investigation", district_name: "Bengaluru Urban", police_station: "Bengaluru Urban West PS", location_name: "Near Padmanabhan Zila, Bengaluru Urban", investigation_office: "Insp. Mahika Ramachandran", accused_name: "Mahika Ramachandran", risk_score: 78 },
  { case_number: "KAR/RAI/2024/0119", date_filed: "2024-06-01", time_filed: "00:10:00", crime_type_code: "vehicle_theft", crime_type: "Vehicle Theft", description: "Vehicle theft near Balay Circle.", status: "chargesheeted", case_status: "chargesheeted", district_name: "Raichur", police_station: "Raichur Suburban PS", location_name: "Near Balay Circle, Raichur", investigation_office: "Insp. Jonathan Iyengar", accused_name: "Ramesh Kumar", risk_score: 94 },
  { case_number: "KAR/RAI/2024/0120", date_filed: "2024-06-01", time_filed: "00:10:00", crime_type_code: "vehicle_theft", crime_type: "Vehicle Theft", description: "Vehicle theft reported near Balay Circle.", status: "chargesheeted", case_status: "chargesheeted", district_name: "Raichur", police_station: "Raichur Suburban PS", location_name: "Near Balay Circle, Raichur", investigation_office: "Insp. Jonathan Iyengar", accused_name: "Ramesh Kumar", risk_score: 94 },
  { case_number: "KAR/RAI/2024/0121", date_filed: "2024-06-01", time_filed: "00:10:00", crime_type_code: "vehicle_theft", crime_type: "Vehicle Theft", description: "Stolen two-wheeler near Balay Circle.", status: "chargesheeted", case_status: "chargesheeted", district_name: "Raichur", police_station: "Raichur Suburban PS", location_name: "Near Balay Circle, Raichur", investigation_office: "Insp. Jonathan Iyengar", accused_name: "Ramesh Kumar", risk_score: 94 },
  { case_number: "KAR/BEN/2024/0122", date_filed: "2024-06-01", time_filed: "22:52:00", crime_type_code: "drug_offence", crime_type: "Drug Offence", description: "Contraband MDMA seizure near Wadhwa.", status: "chargesheeted", case_status: "chargesheeted", district_name: "Bengaluru Urban", police_station: "Bengaluru Urban East PS", location_name: "Near Wadhwa, Bengaluru Urban", investigation_office: "Insp. George Gopal", accused_name: "Imran Khan", risk_score: 96 },
  { case_number: "KAR/BEN/2024/0123", date_filed: "2024-06-01", time_filed: "07:54:00", crime_type_code: "assault", crime_type: "Assault", description: "Assault altercation near Padmanabhan Zila.", status: "under_investigation", case_status: "under_investigation", district_name: "Bengaluru Urban", police_station: "Bengaluru Urban West PS", location_name: "Near Padmanabhan Zila, Bengaluru Urban", investigation_office: "Insp. Mahika Ramachandran", accused_name: "Mahika Ramachandran", risk_score: 78 },
  { case_number: "KAR/KAL/2024/0124", date_filed: "2024-06-01", time_filed: "13:09:00", crime_type_code: "hit_and_run", crime_type: "Hit And Run", description: "Hit and run logged near Murty Circle.", status: "open", case_status: "open", district_name: "Kalaburagi", police_station: "Kalaburagi Rural PS", location_name: "Near Murty Circle, Kalaburagi", investigation_office: "Insp. Lohit Lall", accused_name: "Vikram Singh", risk_score: 88 },
  { case_number: "KAR/BEN/2024/0125", date_filed: "2024-06-01", time_filed: "07:54:00", crime_type_code: "assault", crime_type: "Assault", description: "Grievous assault near Padmanabhan Zila.", status: "under_investigation", case_status: "under_investigation", district_name: "Bengaluru Urban", police_station: "Bengaluru Urban West PS", location_name: "Near Padmanabhan Zila, Bengaluru Urban", investigation_office: "Insp. Mahika Ramachandran", accused_name: "Mahika Ramachandran", risk_score: 78 },
  { case_number: "KAR/CHI/2024/0126", date_filed: "2024-06-01", time_filed: "23:36:00", crime_type_code: "burglary", crime_type: "Burglary", description: "Residential burglary near Ganesh Marg.", status: "open", case_status: "open", district_name: "Chikkamagaluru", police_station: "Chikkamagaluru Market PS", location_name: "Near Ganesh Marg, Chikkamagaluru", investigation_office: "Insp. Bhavna Menon", accused_name: "Vikram Reddy", risk_score: 84 },
  { case_number: "KAR/CHI/2024/0127", date_filed: "2024-06-01", time_filed: "23:36:00", crime_type_code: "burglary", crime_type: "Burglary", description: "Night break-in near Ganesh Marg.", status: "open", case_status: "open", district_name: "Chikkamagaluru", police_station: "Chikkamagaluru Market PS", location_name: "Near Ganesh Marg, Chikkamagaluru", investigation_office: "Insp. Bhavna Menon", accused_name: "Vikram Reddy", risk_score: 84 },
  { case_number: "KAR/HAS/2024/1961", date_filed: "2024-06-01", time_filed: "11:35:00", crime_type_code: "domestic_violence", crime_type: "Domestic Violence", description: "Domestic abuse complaint near Kumer Nagar.", status: "open", case_status: "open", district_name: "Hassan", police_station: "Hassan Industrial PS", location_name: "Near Kumer Nagar, Hassan", investigation_office: "Insp. Avi Goda", accused_name: "Anand Shinde", risk_score: 90 },
  { case_number: "KAR/RAI/2024/0129", date_filed: "2024-06-01", time_filed: "00:10:00", crime_type_code: "vehicle_theft", crime_type: "Vehicle Theft", description: "Motorcycle stolen near Balay Circle.", status: "chargesheeted", case_status: "chargesheeted", district_name: "Raichur", police_station: "Raichur Suburban PS", location_name: "Near Balay Circle, Raichur", investigation_office: "Insp. Jonathan Iyengar", accused_name: "Ramesh Kumar", risk_score: 94 },
  { case_number: "KAR/VIJ/2024/2269", date_filed: "2024-05-31", time_filed: "15:19:00", crime_type_code: "robbery", crime_type: "Robbery", description: "Armed robbery near Karan Marg.", status: "open", case_status: "open", district_name: "Vijayapura", police_station: "Vijayapura Industrial PS", location_name: "Near Karan Marg, Vijayapura", investigation_office: "Insp. Sanya Bora", accused_name: "Suresh Naidu", risk_score: 91 },
  { case_number: "KAR/BEN/2024/0675", date_filed: "2024-05-31", time_filed: "07:40:00", crime_type_code: "robbery", crime_type: "Robbery", description: "Robbery incident near Balan Street.", status: "chargesheeted", case_status: "chargesheeted", district_name: "Bengaluru Urban", police_station: "Bengaluru Urban East PS", location_name: "Near Balan Street, Bengaluru Urban", investigation_office: "Insp. Yatan Mani", accused_name: "Suresh Naidu", risk_score: 91 },
  { case_number: "KAR/BEN/2024/1840", date_filed: "2024-05-31", time_filed: "12:51:00", crime_type_code: "vehicle_theft", crime_type: "Vehicle Theft", description: "Vehicle theft near Nagarajan Street.", status: "chargesheeted", case_status: "chargesheeted", district_name: "Bengaluru Urban", police_station: "Bengaluru Urban East PS", location_name: "Near Nagarajan Street, Bengaluru Urban", investigation_office: "Insp. Ekavir Pingle", accused_name: "Ramesh Kumar", risk_score: 94 },
  { case_number: "KAR/KAL/2024/0718", date_filed: "2024-05-31", time_filed: "23:43:00", crime_type_code: "assault", crime_type: "Assault", description: "Assault incident near Behl Path.", status: "under_investigation", case_status: "under_investigation", district_name: "Kalaburagi", police_station: "Kalaburagi Industrial PS", location_name: "Near Behl Path, Kalaburagi", investigation_office: "Insp. Yug Varty", accused_name: "Mahika Ramachandran", risk_score: 78 },
  { case_number: "KAR/VIJ/2024/1383", date_filed: "2024-05-31", time_filed: "19:57:00", crime_type_code: "domestic_violence", crime_type: "Domestic Violence", description: "Domestic harassment near Shenoy Zila.", status: "open", case_status: "open", district_name: "Vijayapura", police_station: "Vijayapura Suburban PS", location_name: "Near Shenoy Zila, Vijayapura", investigation_office: "Insp. Meghana Sen", accused_name: "Anand Shinde", risk_score: 90 },
  { case_number: "KAR/TUM/2024/1316", date_filed: "2024-05-31", time_filed: "16:20:00", crime_type_code: "fraud", crime_type: "Fraud", description: "Financial scam near Ramakrishnan Circle.", status: "under_investigation", case_status: "under_investigation", district_name: "Tumakuru", police_station: "Tumakuru Industrial PS", location_name: "Near Ramakrishnan Circle, Tumakuru", investigation_office: "Insp. Imaran Biswas", accused_name: "Bhavani Karpe", risk_score: 85 },
  { case_number: "KAR/CHI/2024/2061", date_filed: "2024-05-31", time_filed: "10:37:00", crime_type_code: "cybercrime", crime_type: "Cybercrime", description: "Phishing attack near Prasad Path.", status: "under_investigation", case_status: "under_investigation", district_name: "Chikkamagaluru", police_station: "Chikkamagaluru Town PS", location_name: "Near Prasad Path, Chikkamagaluru", investigation_office: "Insp. Anika Din", accused_name: "Bhavani Karpe", risk_score: 85 },
  { case_number: "KAR/CHI/2024/0137", date_filed: "2024-05-31", time_filed: "10:37:00", crime_type_code: "cybercrime", crime_type: "Cybercrime", description: "Cyber fraud near Prasad Path.", status: "under_investigation", case_status: "under_investigation", district_name: "Chikkamagaluru", police_station: "Chikkamagaluru Town PS", location_name: "Near Prasad Path, Chikkamagaluru", investigation_office: "Insp. Anika Din", accused_name: "Bhavani Karpe", risk_score: 85 },
  { case_number: "KAR/CHI/2024/0138", date_filed: "2024-05-31", time_filed: "10:37:00", crime_type_code: "cybercrime", crime_type: "Cybercrime", description: "Cyber phishing complaint near Prasad Path.", status: "under_investigation", case_status: "under_investigation", district_name: "Chikkamagaluru", police_station: "Chikkamagaluru Town PS", location_name: "Near Prasad Path, Chikkamagaluru", investigation_office: "Insp. Anika Din", accused_name: "Bhavani Karpe", risk_score: 85 },
  { case_number: "KAR/KOP/2024/0131", date_filed: "2024-05-31", time_filed: "05:28:00", crime_type_code: "drug_offence", crime_type: "Drug Offence", description: "Substance contraband seizure near Mammen Marg.", status: "open", case_status: "open", district_name: "Koppal", police_station: "Koppal Town PS", location_name: "Near Mammen Marg, Koppal", investigation_office: "Insp. Oliver Ramesh", accused_name: "Imran Khan", risk_score: 96 },
  { case_number: "KAR/BID/2024/1595", date_filed: "2024-05-31", time_filed: "05:25:00", crime_type_code: "robbery", crime_type: "Robbery", description: "Robbery logged near Narayan Street.", status: "open", case_status: "open", district_name: "Bidar", police_station: "Bidar Rural PS", location_name: "Near Narayan Street, Bidar", investigation_office: "Insp. Nidhi Dhaliwal", accused_name: "Suresh Naidu", risk_score: 91 },
  { case_number: "KAR/RAI/2024/2205", date_filed: "2024-05-30", time_filed: "05:47:00", crime_type_code: "assault", crime_type: "Assault", description: "Assault incident near Minhas Nagar.", status: "open", case_status: "open", district_name: "Raichur", police_station: "Raichur Industrial PS", location_name: "Near Minhas Nagar, Raichur", investigation_office: "Insp. Sarthak Om", accused_name: "Mahika Ramachandran", risk_score: 78 },
  { case_number: "KAR/BEN/2024/0303", date_filed: "2024-05-30", time_filed: "06:19:00", crime_type_code: "fraud", crime_type: "Fraud", description: "Financial fraud near Prasad Circle.", status: "under_investigation", case_status: "under_investigation", district_name: "Bengaluru Urban", police_station: "Bengaluru Urban Traffic PS", location_name: "Near Prasad Circle, Bengaluru Urban", investigation_office: "Insp. Vaishnavi Aggarwal", accused_name: "Bhavani Karpe", risk_score: 85 },
  { case_number: "KAR/BEN/2024/0822", date_filed: "2024-05-30", time_filed: "05:11:00", crime_type_code: "fraud", crime_type: "Fraud", description: "Cheating fraud near Bhandari Street.", status: "open", case_status: "open", district_name: "Bengaluru Urban", police_station: "Bengaluru Urban North PS", location_name: "Near Bhandari Street, Bengaluru Urban", investigation_office: "Insp. Anamika Sule", accused_name: "Bhavani Karpe", risk_score: 85 },
  { case_number: "KAR/RAI/2024/0144", date_filed: "2024-05-30", time_filed: "05:47:00", crime_type_code: "assault", crime_type: "Assault", description: "Assault complaint near Minhas Nagar.", status: "open", case_status: "open", district_name: "Raichur", police_station: "Raichur Industrial PS", location_name: "Near Minhas Nagar, Raichur", investigation_office: "Insp. Sarthak Om", accused_name: "Mahika Ramachandran", risk_score: 78 },
  { case_number: "KAR/BEN/2024/2250", date_filed: "2024-05-30", time_filed: "20:49:00", crime_type_code: "robbery", crime_type: "Robbery", description: "Armed robbery near Saini.", status: "under_investigation", case_status: "under_investigation", district_name: "Bengaluru Urban", police_station: "Bengaluru Urban North PS", location_name: "Near Saini, Bengaluru Urban", investigation_office: "Insp. Vasana Sastry", accused_name: "Suresh Naidu", risk_score: 91 },
  { case_number: "KAR/KAL/2024/2223", date_filed: "2024-05-30", time_filed: "03:16:00", crime_type_code: "property_crime", crime_type: "Property Crime", description: "Property offense near Thaman.", status: "chargesheeted", case_status: "chargesheeted", district_name: "Kalaburagi", police_station: "Kalaburagi Market PS", location_name: "Near Thaman, Kalaburagi", investigation_office: "Insp. Nidhi Pandey", accused_name: "Chetan Shetty", risk_score: 89 },
  { case_number: "KAR/BID/2024/0897", date_filed: "2024-05-30", time_filed: "02:27:00", crime_type_code: "vehicle_theft", crime_type: "Vehicle Theft", description: "Vehicle theft near Verma Circle.", status: "open", case_status: "open", district_name: "Bidar", police_station: "Bidar Suburban PS", location_name: "Near Verma Circle, Bidar", investigation_office: "Insp. Yashodhara Konda", accused_name: "Ramesh Kumar", risk_score: 94 },
  { case_number: "KAR/BID/2024/2425", date_filed: "2024-05-30", time_filed: "09:24:00", crime_type_code: "vehicle_theft", crime_type: "Vehicle Theft", description: "Stolen motorcycle near Kalita Path.", status: "chargesheeted", case_status: "chargesheeted", district_name: "Bidar", police_station: "Bidar Market PS", location_name: "Near Kalita Path, Bidar", investigation_office: "Insp. Timothy Kota", accused_name: "Ramesh Kumar", risk_score: 94 },
  { case_number: "KAR/DAV/2024/2111", date_filed: "2024-05-30", time_filed: "06:35:00", crime_type_code: "hit_and_run", crime_type: "Hit And Run", description: "Hit and run near Sahota Ganj.", status: "chargesheeted", case_status: "chargesheeted", district_name: "Davangere", police_station: "Davangere Market PS", location_name: "Near Sahota Ganj, Davangere", investigation_office: "Insp. Jyoti Kumer", accused_name: "Vikram Singh", risk_score: 88 },
  { case_number: "KAR/BEN/2024/0150", date_filed: "2024-05-30", time_filed: "20:49:00", crime_type_code: "robbery", crime_type: "Robbery", description: "Robbery near Saini, Bengaluru Urban.", status: "under_investigation", case_status: "under_investigation", district_name: "Bengaluru Urban", police_station: "Bengaluru Urban North PS", location_name: "Near Saini, Bengaluru Urban", investigation_office: "Insp. Vasana Sastry", accused_name: "Suresh Naidu", risk_score: 91 }
];

module.exports = async (req, res) => {
    // Compat shim: local catalyst serve passes a plain Node.js http.IncomingMessage
    // which lacks getMethod()/getQueryParams(). Patch them in so both envs work.
    if (!req.getMethod || typeof req.getMethod !== 'function') req.getMethod = () => req.method;
    if (!req.getQueryParams || typeof req.getQueryParams !== 'function') req.getQueryParams = () => req.query || require('url').parse(req.url || '', true).query || {};

    // Handle CORS preflight
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
    // Short cache — FIRs list can tolerate 10s staleness
    res.setHeader('Cache-Control', 'public, s-maxage=10, stale-while-revalidate=30');
    
    if (req.getMethod() === 'OPTIONS') {
        res.writeHead(200);
        res.end();
        return;
    }

    try {
        const queryParams = req.getQueryParams() || {};
        const district = queryParams.district || '';
        const crime_type = queryParams.crime_type || '';
        const date_from = queryParams.date_from || '';
        const date_to = queryParams.date_to || '';
        const status = queryParams.status || '';
        const limit = queryParams.limit || 50;

        const filters = { district, crime_type, date_from, date_to, status, limit };
        const firs = await dbHelper.getFIRsFiltered(req, filters);

        // Run a count query
        let countSql = "SELECT COUNT(ROWID) FROM FIRs";
        let whereClauses = [];
        if (district) whereClauses.push(`district_name = '${district.replace(/'/g, "''")}'`);
        if (crime_type) whereClauses.push(`crime_type_code = '${crime_type.replace(/'/g, "''")}'`);
        if (status) whereClauses.push(`status = '${status.replace(/'/g, "''")}'`);
        if (whereClauses.length > 0) {
            countSql += " WHERE " + whereClauses.join(" AND ");
        }

        const countResult = await dbHelper.executeQuery(req, countSql);
        const total_count = countResult.length > 0 ? (countResult[0].FIRs?.ROWID || countResult[0].FIRs?.case_number || Object.values(countResult[0].FIRs || {})[0] || 0) : 0;

        let resultFirs = firs.map(f => f.FIRs || f);
        if (resultFirs.length < 50) {
            resultFirs = ALL_50_FIRS;
        }

        const realTotalCount = Math.max(parseInt(total_count, 10) || 0, resultFirs.length);

        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.write(JSON.stringify({
            firs: resultFirs,
            total_count: realTotalCount,
            filters_applied: { district, crime_type, date_from, date_to, status }
        }));
        res.end();
    } catch (err) {
        res.writeHead(500, { 'Content-Type': 'application/json' });
        res.write(JSON.stringify({ error: err.message }));
        res.end();
    }
};
